### ISSUE TITLE
Free Cam Not Going Through Blocks

### ISSUE THREAD

**Issue by ghost** [MinecraftFreecam/Freecam#156]
I was using freecam from forge it was doing well but when I switched to feather lancher and fabric mode it is working but not going through blocks pls reosloeve this issue for sodium and feather lancher

**Comment by MattSturgeon** [comment]
Thanks for reporting this issue. We'll need a little more information to resolve this.

**Are you using the Modrinth Edition?**
- That version can only bypass collision in singleplayer (or when _op_) due to Modrinth's rules.
- You can try the Curseforge or GitHub release instead.

**Otherwise:**
- What version of Freecam has the issue?
- What Minecraft version are you using?
- What other mods are you using alongside Freecam?
- Does disabling any of the other mods resolve the issue? If so, which?

**Comment by MattSturgeon** [comment]
Closing as stale, feel free to re-open with more information

**Comment by UnTamed-Fury** [comment]
I have same problem and I'm using modrinth addition fabric 1.20.4 on a server and my all setting on no collision.

**Comment by MattSturgeon** [comment]
@UnTamed-Fury that's expected behaviour for Modrinth Edition.

If you want to be able to bypass collision on multiplayer servers, then you'll need to either be "op" or download Freecam from GitHub or CurseForge.

**Comment by UnTamed-Fury** [comment]
This problem is also happening in CurseForge version. I'll try more releases.  🙂

**Comment by MattSturgeon** [comment]
@UnTamed-Fury could you open a new issue describing your issue in more detail?

It may well be a compatibility issue, so consider testing whether you have the bug with various combinations of other mods as well as _just_ Freecam on its own.

**Comment by santuprasad** [comment]
you just need to change the settings. Open free cam settings and toggle yes to the collision options, Ignore all collisions, ignore transparent block and ignore openable blocks. change all these to yes. it will work. 

To access free cam settings, add a key bind to the Config GUI. Options-Controls-Key binds.
