### ISSUE TITLE
Build Mode

### ISSUE THREAD

**Issue by Seshua** [MinecraftFreecam/Freecam#193]
### Description of the feature

Not sure if this would be out of the scope of this mod, or might seem a bit cheaty. My idea is a Build mode, that lets you fly around but also allows you to build, so while doing complicated builds its makes them less..complicated..lol.

### Why is this useful?

Solves complicated building projects.

### Freecam version

1.2.3

**Comment by MattSturgeon** [comment]
Thanks for your suggestion!

We do already have an "allow interact" setting, but you'll notice that you're only able to interact with things that are _very_ close to your player.

This isn't a restriction we've added, rather it's built into vanilla Minecraft's server.

Since we're not planning to make Freecam a server-side mod, I'll mark this as won't fix.
