### ISSUE TITLE
The mod is detectable by servers.

### ISSUE THREAD

**Issue by zisis912** [MinecraftFreecam/Freecam#196]
### Description of the issue

When joining a server like `play.ccnetmc.com` it is possible for the server to detect the freecam mod and instantly ban the user for it. 

The fabric loader by default does not expose a mod list to the server, so I am guessing this is a freecam feature.

### Expected behavior

I expect the mod to function like any other mod, and not send any information to the server.

### Steps to reproduce

1. go to `play.ccnetmc.com` with freecam mod on. 
2. get banned for it 5 seconds after you join

### How prevalent is the issue?

unsure, i have not done extensive testing

### Freecam version

1.2.3 - 1.20.4

### Are you using "Modrinth Edition"?

No

### Minecraft version

1.20.4

### Modding platform

- [X] Fabric
- [ ] Neoforge
- [ ] Forge

**Comment by MattSturgeon** [comment]
Thanks for reporting this. It is a particularly interesting issue!

I've updated the title as this has nothing to do with telemetry. We don't have any telemetry. AFAIK neither does Fabric.


> The fabric loader by default does not expose a mod list to the server

Correct

> I am guessing this is a freecam feature

I'm afraid not.

It turns out, that server is using [this exploit](https://github.com/JustAlittleWolf/ModDetectionPreventer?tab=readme-ov-file#the-vulnerability) to detect mods based on translation keys being installed on the client.

---

Since that server doesn't permit the use of Freecam _anyway_ and the only issue on our end is that we provide translatable text, I'm going to close this.

I do find it frustrating that servers will ban players for having tools _installed_ even without them being used. That said, I appreciate the _use_ of Freecam would be difficult to detect, so I understand why they take that approach.

**Comment by zisis912** [comment]
Wow, thank you so much for the explanation!
How did you come across this mod and exploit? I searched but couldnt find anything regarding this!

**Comment by RobinBr26** [comment]
@zisis912 Fixed in my fork:
https://github.com/RobinBr26/Freecam
