### ISSUE TITLE
Feature request: Allow players to open/view chests and shulkers

### ISSUE THREAD

**Issue by fartfartfarty** [MinecraftFreecam/Freecam#98]
It would be useful to see how much your farm has gathered from your afk spot without moving at all, only for singleplayer though.

**Comment by Tom-Sumner** [comment]
Cannot interact with blocks outside of the players render distance (I'm 90% sure).

However, I am working on a mod myself for this purpose, I will let you know when it's done.

**Comment by MattSturgeon** [comment]
**This option already exists:** look for `Freecam Options` -> `Utility Options` -> `Allow Interaction`.

Note, however, that it won't be very useful for checking farm output from an AFK spot. This is due to fundamental range restrictions imposed by the server (explained below).

> Cannot interact with blocks outside of the players render distance

Render distance is irrelevant, as you cant even **see** anything outside of it...

As for interaction range, in simple terms it depends on the server. Vanilla servers will let the client interact with anything relatively close to the player (within ~5 blocks). Many servers have "anti-cheat" modules that also check for things like line-of-sight.
